#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

export $TERM="kitty"

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -model pc104 -layout us,gr -option grp:lalt_lshift_toggle
nitrogen --set-zoom-fill ~/Pictures/wallpapers/wp4413782-forest-light-wallpapers.jpg
picom &
xmobar /home/mtsap/.config/xmonad/xmobar-config &
# ~/.config/polybar/launch.sh
exec /home/mtsap/.local/bin/xmonad
