#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define DEBOUNCE 10
#define NO_ACTION_ONESHOT
#define CAPS_WORD_IDLE_TIMEOUT 3000
