hl.on("hyprland.start", function()
    hl.exec_cmd("killall -q waybar;sleep .5 && waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprctl setcursor Borealis-cursors 24")
    hl.exec_cmd("udiskie &")
    hl.exec_cmd("asusctl anime image -p /home/mtsap/Pictures/f14-11.png -s 1 -a 3.5")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("openrgb --startminimized --profile ~/.config/OpenRGB/homeport.orp")
    hl.exec_cmd("hypridle")
end)
